### ISSUE TITLE
Can we please have multiple proto path fields when sources in different folders like vendor and proto

### ISSUE THREAD

**Issue by alapativ2** [Dancheg97/grpc-clicker#136]

**Comment by Dancheg97** [comment]
If you can do that with grpcurl, more likely that you can do that with clicker aswell. You can try to add custom flag with `Custom flags` area similarly, like with grpcurl command. You can provide the protos, so that i can test your case locally and make required adjustments for you.
![Screenshot from 2023-05-27 15-18-51](https://github.com/Dancheg97/grpc-clicker/assets/58640116/e7eaf27d-5d13-4b2b-bdee-b1f8ce3d4b44)
Tell me if this does not help.
